"""
Non-model reference numbers for the v4 item set (CPU only; no model is called).

  * key distributions, chance and majority-class rates per phase
  * TCM: what a label-only lookup (DSCR category -> action class, ignoring the stated timing) can reach, versus
    the full rule (category + timing) that defines the key. The gap is the room in which a model can show that it
    uses the second fact.
  * PJRF: the recorded one-year-mortality rate and the Brier score of constant forecasts, plus a leave-one-out
    logistic model on the stated clinical facts (age, MGMT, extent of resection, weeks since surgery). If that model
    cannot beat the base rate, no forecaster can be expected to on these facts, which bounds what PJRF can show.
  * rule-vs-expert agreement for the DSCR category (selection_report.json), the answerability proxy
    for the expert RANO labels of v3.

Writes results/lumiere_v4_baselines.{md,json}.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

import numpy as np

from src.lumiere_loader import load_lumiere

PHASES = ["AIA", "LIL", "DSCR", "PJRF", "TCM"]
BINS = [0.10, 0.30, 0.50, 0.80]


def _logistic_loo(X: np.ndarray, y: np.ndarray, l2: float = 1.0, iters: int = 200) -> np.ndarray:
    """Leave-one-out predicted probabilities from an L2-regularised logistic regression (Newton steps)."""
    n = len(y)
    out = np.zeros(n)
    for i in range(n):
        tr = np.arange(n) != i
        mu, sd = X[tr].mean(0), X[tr].std(0) + 1e-9
        A = np.c_[np.ones(tr.sum()), (X[tr] - mu) / sd]
        w = np.zeros(A.shape[1])
        reg = l2 * np.eye(A.shape[1])
        reg[0, 0] = 0.0
        for _ in range(iters):
            p = 1 / (1 + np.exp(-A @ w))
            g = A.T @ (p - y[tr]) + reg @ w
            H = A.T @ (A * (p * (1 - p))[:, None]) + reg
            step = np.linalg.solve(H, g)
            w -= step
            if np.abs(step).max() < 1e-8:
                break
        a = np.r_[1.0, (X[i] - mu) / sd]
        out[i] = 1 / (1 + np.exp(-a @ w))
    return out


def brier(p: np.ndarray, y: np.ndarray) -> float:
    return float(np.mean((p - y) ** 2))


def auc(p: np.ndarray, y: np.ndarray) -> float:
    pos, neg = p[y == 1], p[y == 0]
    if len(pos) == 0 or len(neg) == 0:
        return float("nan")
    return float((np.sum(pos[:, None] > neg[None, :]) + 0.5 * np.sum(pos[:, None] == neg[None, :])) / (len(pos) * len(neg)))


def main() -> None:
    cases = load_lumiere(item_set="v4", include_unreviewed=True)
    res: dict = {"n_cases": len(cases)}
    md = ["# LUMIERE v4 non-model baselines", "", f"Generated by `tools/lumiere_v4_baselines.py`; {len(cases)} patients.", ""]

    md += ["## Key distributions", "", "| Phase | n | options | chance | majority-key share | key counts |", "|---|---|---|---|---|---|"]
    res["keys"] = {}
    for ph in PHASES:
        qs = [c["phases"][ph][0] for c in cases if ph in c["phases"]]
        if ph == "PJRF":
            y = [q["forecast"]["outcome"] for q in qs]
            cnt = Counter(y)
            res["keys"][ph] = {"n": len(qs), "outcome_counts": dict(cnt)}
            md.append(f"| PJRF | {len(qs)} | 4 probability bins | (forecast) | died within horizon: {cnt[1]}/{len(qs)} | outcome {dict(cnt)} |")
            continue
        cnt = Counter(q["correct_answer_text"] for q in qs)
        top = cnt.most_common(1)[0][1]
        res["keys"][ph] = {"n": len(qs), "counts": dict(cnt), "majority": top / len(qs), "chance": 1 / len(qs[0]["options"])}
        md.append(f"| {ph} | {len(qs)} | {len(qs[0]['options'])} | {100 / len(qs[0]['options']):.0f}% | {100 * top / len(qs):.1f}% ({top}/{len(qs)}) | "
                  + "; ".join(f"{k[:40]}: {v}" for k, v in cnt.most_common()) + " |")

    # ---- TCM: label-only lookup versus the full rule
    tcm = [c["phases"]["TCM"][0] for c in cases]
    classes = Counter(q["tcm_rule"]["class"] for q in tcm)
    pd_items = [q for q in tcm if q["tcm_rule"]["rano"] == "progressive disease"]
    lookup_hits = sum(q["tcm_rule"]["class"] in ("continue", "escalate") for q in tcm)   # label-only rule answers escalate for PD
    lookup_alt = sum(q["tcm_rule"]["class"] in ("continue", "confirm") for q in tcm)     # ... or confirm for PD
    res["tcm"] = {"n": len(tcm), "classes": dict(classes), "pd_items": len(pd_items),
                  "label_only_lookup_escalate": lookup_hits / len(tcm), "label_only_lookup_confirm": lookup_alt / len(tcm),
                  "full_rule": 1.0}
    md += ["", "## TCM: label-only lookup versus the full rule", "",
           f"Key classes: {dict(classes)}. A model that maps the upstream category to an action class but ignores the stated "
           f"weeks since chemoradiotherapy picks one class for every progressive-disease item: escalate everywhere gives "
           f"**{100 * lookup_hits / len(tcm):.1f}%**, confirm-first everywhere **{100 * lookup_alt / len(tcm):.1f}%** "
           f"(n={len(tcm)}). The rule that defines the key (category + timing) gives 100% by construction. "
           f"Items on which the timing decides ({len(pd_items)} progressive-disease items) are where a lookup-only model fails.", ""]

    # ---- PJRF
    pj = [(c["id"], c["phases"]["PJRF"][0]) for c in cases if "PJRF" in c["phases"]]
    y = np.array([q["forecast"]["outcome"] for _, q in pj], float)
    facts = {}
    for c in cases:
        fp = Path("data/lumiere/v4/facts") / f"{c['id']}.json"
        facts[c["id"]] = json.loads(fp.read_text())
    rows = []
    for pid, q in pj:
        f = facts[pid]
        demo = f["record"]["demo"]
        try:
            age = float(demo["Age at surgery (years)"])
        except (TypeError, ValueError):
            age = np.nan
        mg = str(demo.get("MGMT qualitative", "")).strip().lower()
        rows.append([age, 1.0 if mg == "methylated" else 0.0, 1.0 if mg in ("methylated", "not methylated") else 0.0,
                     1.0 if f["record"].get("extent") == "complete" else 0.0, float(f["selected"]["weeks_since_surgery"])])
    X = np.array(rows)
    X[:, 0] = np.where(np.isnan(X[:, 0]), np.nanmean(X[:, 0]), X[:, 0])
    base = float(y.mean())
    loo_base = np.array([np.delete(y, i).mean() for i in range(len(y))])
    p_lr = _logistic_loo(X, y)
    res["pjrf"] = {"n": len(y), "base_rate": base, "brier_constant_base_rate_loo": brier(loo_base, y),
                   "brier_constant_0.5": brier(np.full_like(y, 0.5), y), "brier_logistic_loo": brier(p_lr, y),
                   "auc_logistic_loo": auc(p_lr, y),
                   "brier_logistic_loo_binned": brier(np.array([min(BINS, key=lambda b: abs(b - p)) for p in p_lr]), y)}
    md += ["## PJRF: forecast reference scores", "",
           f"n = {len(y)}; died within {pj[0][1]['forecast']['horizon_weeks']} weeks of the scan: {int(y.sum())} ({100 * base:.1f}%).", "",
           "| Forecast | Brier | AUC |", "|---|---|---|",
           f"| constant 0.5 | {res['pjrf']['brier_constant_0.5']:.3f} | 0.500 |",
           f"| constant base rate (leave-one-out) | {res['pjrf']['brier_constant_base_rate_loo']:.3f} | 0.500 |",
           f"| logistic on age, MGMT, resection extent, weeks since surgery (leave-one-out) | {res['pjrf']['brier_logistic_loo']:.3f} | {res['pjrf']['auc_logistic_loo']:.3f} |",
           f"| same, snapped to the four answer-bin midpoints | {res['pjrf']['brier_logistic_loo_binned']:.3f} | (same) |", "",
           "Brier skill of a model forecast is reported against the leave-one-out constant base rate. A forecaster that cannot beat "
           "that constant on these facts is not showing prognostic reasoning."]

    # ---- DSCR rule vs expert
    sel = json.loads(Path("data/lumiere/v4/selection_report.json").read_text())
    conc = sel["rule_vs_expert_concordance"]
    tot = conc["n"] + sel["n_undetermined_followups"]
    res["dscr_rule_vs_expert"] = conc
    md += ["", "## DSCR: image-derived category versus the expert RANO rating (all first-line follow-ups)", "",
           f"Of {tot} first-line follow-ups (one per rated, imaged timepoint before any second surgery), "
           f"{sel['n_undetermined_followups']} ({100 * sel['n_undetermined_followups'] / tot:.0f}%) are undetermined by enhancement (no measurable "
           f"enhancing disease on the baseline or the nadir scan) and {conc['concordant']} ({100 * conc['concordant'] / tot:.0f}%) have the same "
           f"category under the enhancement rule and the expert rating; the rest disagree. By expert label:", "",
           "| Expert label | follow-ups | same category | enhancement undetermined | different category |", "|---|---|---|---|---|"]
    for lab, d in conc["by_expert_label"].items():
        und = sel["undetermined_by_expert"].get(lab, 0)
        n_lab = d["n"] + und
        md.append(f"| {lab} | {n_lab} | {d['concordant']} ({100 * d['concordant'] / n_lab:.0f}%) | {und} | {d['n'] - d['concordant']} |")
    md += ["", f"Selected items: {sel['selected_expert_agrees']}/{sel['n_selected']} agree with the expert rating (selection prefers agreeing follow-ups)."]

    # ---- measurement check against the rater's recorded target-lesion measurements
    import re
    from scipy.stats import spearmanr
    from src.lumiere_v4 import enumerate_candidates
    ours, theirs = [], []
    for r in enumerate_candidates().values():
        for c in r["candidates"]:
            m = re.search(r"(\d+)\s*mm\s*x\s*(\d+)\s*mm", str(c["rationale"]))
            if m and c["bp_fu"] > 0:
                theirs.append(int(m.group(1)) * int(m.group(2)))
                ours.append(c["bp_fu"])
    ours, theirs = np.array(ours, float), np.array(theirs, float)
    rho = spearmanr(ours, theirs)
    res["bp_vs_rater"] = {"n": len(ours), "spearman": float(rho.statistic), "p": float(rho.pvalue),
                          "median_ratio_ours_over_rater": float(np.median(ours / theirs)),
                          "iqr_ratio": [float(x) for x in np.percentile(ours / theirs, [25, 75])]}
    md += ["", "## Measurement check", "",
           f"Our automated bidimensional product of the largest enhancing component at the follow-up slice versus the product of the two "
           f"diameters the rater recorded for the target lesion (LUMIERE rationale, {len(ours)} follow-ups with both): Spearman "
           f"{rho.statistic:.2f} (p = {rho.pvalue:.1e}); ours is a median {np.median(ours / theirs):.2f} times the rater's "
           f"(IQR {np.percentile(ours / theirs, 25):.2f} to {np.percentile(ours / theirs, 75):.2f})."]

    Path("results/lumiere_v4_baselines.md").write_text("\n".join(md))
    Path("results/lumiere_v4_baselines.json").write_text(json.dumps(res, indent=2, default=float))
    print("\n".join(md))


if __name__ == "__main__":
    main()
