"""
One authoritative source for every number the paper quotes (paper/review.md, concern 5).

Reads the raw data and the result files and writes, under paper/latex/generated/:
  numbers.tex        \\newcommand macros for every scalar the text cites (v3 audit and v4)
  tab_v3_*.tex       the v3 tables (text-only, options-only, gating-causality)
  tab_v4_*.tex       the v4 tables (baselines, E1-E5); cells read "--" until the v4 runs exist
  numbers.json       the same scalars, for checking

Nothing here is typed by hand: the paper cites macros and \\input's tables. Run after any change to the results:
  python -m tools.paper_numbers            # regenerate
  python -m tools.paper_numbers --check    # also fail if the .tex still contains a known stale number
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from math import comb
from pathlib import Path

import numpy as np

import config.lumiere as lcfg
from src.lumiere_labels import canonical_answer_text

OUT = Path("paper/latex/generated")
MODELS = ["MedGemma-4B", "Gemma-3-12B", "Gemma-3-27B", "Llama-4-Scout"]
TAG = {"MedGemma-4B": "MedGemma", "Gemma-3-12B": "GemmaTwelve", "Gemma-3-27B": "GemmaTwentySeven", "Llama-4-Scout": "Scout"}
SHORT = {"MedGemma-4B": "MedGemma-4B", "Gemma-3-12B": "Gemma-3-12B", "Gemma-3-27B": "Gemma-3-27B", "Llama-4-Scout": "Llama-4-Scout"}
PHASES = ["AIA", "LIL", "DSCR", "PJRF", "TCM"]
STALE = [r"63\.5", r"33 of 33", r"(?<!which gave )50 of 52", r"48 and 52", r"33 progressive", r"14\\%\)"]   # figures that came from the label-spelling bug or typos


def load(p: str):
    fp = Path(p)
    return json.loads(fp.read_text()) if fp.exists() else None


def binom_sf(k: int, n: int, p: float) -> float:
    """P(X >= k), X ~ Binomial(n, p)."""
    return sum(comb(n, i) * p ** i * (1 - p) ** (n - i) for i in range(k, n + 1))


def f1(x: float) -> str:
    return f"{x:.1f}"


def signed(x: float) -> str:
    return f"{x:+.1f}".replace("-", "$-$")


def tabular(colspec: str, header: list[str], rows: list[str], size: str = "") -> str:
    """A complete tabular (an \\input inside a tabular breaks booktabs rules, so the whole environment is generated)."""
    return (f"{size}\\begin{{tabular}}{{{colspec}}}\n\\toprule\n" + "\n".join(header) + "\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


class Macros:
    def __init__(self):
        self.d: dict[str, str] = {}

    def add(self, name: str, value) -> None:
        assert re.fullmatch(r"[A-Za-z]+", name), f"macro names are letters only: {name}"
        self.d[name] = str(value)

    def tex(self) -> str:
        return "% generated by tools/paper_numbers.py; do not edit\n" + "\n".join(
            f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in sorted(self.d.items())) + "\n"


def cohort(mc: Macros) -> None:
    for tag, d in (("Fifty", "data/lumiere/facts"), ("Vthree", "data/lumiere/v3/facts")):
        ps = sorted(Path(d).glob("Patient-*.json"))
        cnt = Counter(json.loads(p.read_text())["phase_facts"]["DSCR"]["rating_code"] for p in ps)
        mc.add(f"nPat{tag}", len(ps))
        for code, name in (("PD", "PD"), ("SD", "SD"), ("PR", "PR"), ("CR", "CR")):
            mc.add(f"dscr{tag}{name}", cnt[code])
    n3 = int(mc.d["nPatVthree"])
    mc.add("dscrMajorityCount", mc.d["dscrVthreePD"])
    mc.add("dscrMajorityPct", f1(100 * int(mc.d["dscrVthreePD"]) / n3))
    mc.add("nPatAll", 91)
    mc.add("nPatEligible", 55)


def v3_tables(mc: Macros) -> None:
    rv = load("results/lumiere_reviewer_stats.json")
    gs = load("results/lumiere_gating_stats.json")
    tl = load("results/lumiere_tcm_lookup.json")
    OUT.mkdir(parents=True, exist_ok=True)
    maj = int(mc.d["dscrVthreePD"]) / int(mc.d["nPatVthree"])
    # text-only accuracy table
    rows = []
    for m in ["Llama-4-Scout", "Gemma-3-27B", "Gemma-3-12B", "MedGemma-4B"]:
        a = rv["accuracy"][m]
        rows.append(f"{SHORT[m]} & {f1(100 * a['acc_img'])} & {f1(100 * a['acc_txt'])} & "
                    f"{signed(100 * a['diff'])} [{signed(100 * a['ci'][0])}, {signed(100 * a['ci'][1])}] \\\\")
        mc.add(f"vthreeDiff{TAG[m]}", signed(100 * a["diff"]))
    (OUT / "tab_v3_textonly.tex").write_text(tabular("lccc", ["Model & Image & Text-only & $\\Delta$ [95\\% CI] \\\\"], rows))
    # DSCR accuracy against the majority rate
    for m in MODELS:
        o = gs["options"][m]["phases"]["DSCR"]
        k = round(o["acc_own_image"] * 52)
        tag = TAG[m]
        mc.add(f"vthreeDscrAcc{tag}", f1(100 * o["acc_own_image"]))
        mc.add(f"vthreeDscrP{tag}", f"{binom_sf(k, 52, maj):.2f}")
    # options-only table
    rows = []
    for m in MODELS:
        for i, ph in enumerate(PHASES):
            o = gs["options"][m]["phases"][ph]
            dag = "$^\\dagger$" if o.get("flagged_parse_errors") else ""
            rows.append(f"{SHORT[m] if i == 0 else ''} & {ph} & {f1(100 * o['acc_options_only'])}{dag} & {f1(100 * o['acc_no_chain'])} & "
                        f"{f1(100 * o['acc_own_image'])} & {o['parse_errors']} \\\\")
    (OUT / "tab_v3_optonly.tex").write_text(tabular("llcccc", ["Model & Phase & Opt.-only & No chain & Own-img & Unpars. \\\\"], rows, "\\scriptsize\n"))
    # gating table: c / w / a for TCM and DSCR, ablation deltas
    rows = []
    for m in MODELS:
        t = gs["gating"][m]["phases"]["TCM"]["acc"]
        d = gs["gating"][m]["phases"]["DSCR"]["acc"]
        ab = gs["ablation"][m]
        star = lambda c: "$^{*}$" if c["ci"][0] > 0 or c["ci"][1] < 0 else ""
        di, de = ab["incl-DSCR"]["correct-incorrect"], ab["excl-DSCR"]["correct-incorrect"]
        rows.append(f"{SHORT[m]} & {round(100 * t['correct'])}/{round(100 * t['incorrect'])}/{round(100 * t['absent'])} & "
                    f"{signed(100 * di['diff'])}{star(di)} & {signed(100 * de['diff'])}{star(de)} & "
                    f"{round(100 * d['correct'])}/{round(100 * d['incorrect'])}/{round(100 * d['absent'])} \\\\")
        tag = TAG[m]
        full = gs["gating"][m]["phases"]["TCM"]["contrasts"]["correct-incorrect"]
        mc.add(f"vthreeTcmGap{tag}", f1(100 * full["diff"]))
        mc.add(f"vthreeTcmGapP{tag}", f"{full['mcnemar_p']:.3f}")
        mc.add(f"vthreeTcmDscrOnly{tag}", signed(100 * di["diff"]))
        mc.add(f"vthreeTcmNoDscr{tag}", signed(100 * de["diff"]))
        dc = gs["gating"][m]["phases"]["DSCR"]["contrasts"]["correct-absent"]
        mc.add(f"vthreeDscrCtxHurt{tag}", signed(100 * dc["diff"]))
        mc.add(f"vthreeDscrCtxHurtP{tag}", f"{dc['mcnemar_p']:.3f}")
    (OUT / "tab_v3_gating.tex").write_text(tabular("lcccc", [" & \\multicolumn{3}{c}{TCM} & DSCR \\\\", "\\cmidrule(lr){2-4}\\cmidrule(lr){5-5}",
        "Model & c / w / a & $\\Delta_{\\text{DSCR}}$ & $\\Delta_{\\text{no DSCR}}$ & c / w / a \\\\"], rows))
    # TCM label lookup
    k = tl["key"]
    for name, val in (("tcmAgree", k["agree"]), ("tcmN", k["n"]), ("tcmPdN", k["pd_n"]), ("tcmPdEsc", k["pd_escalate"]),
                      ("tcmNonN", k["nonpd_n"]), ("tcmNonCont", k["nonpd_continue"]), ("tcmClassUnique", k["class_unique"])):
        mc.add(name, val)
    for m in MODELS:
        tag = TAG[m]
        f = tl["follow"][m]
        for cond in ("correct", "incorrect", "absent"):
            v = f[cond]
            mc.add(f"tcmFollow{cond.capitalize()}{tag}", v if isinstance(v, (int, str)) else v.get("escalate", v))
    # donor test
    perm = rv["counterfactual"]["pooled"]["donor_permutation"]
    mc.add("permObserved", perm["observed"])
    mc.add("permN", perm["n"])
    mc.add("permMean", f1(perm["perm_mean"]))
    mc.add("permLo", int(perm["perm_lo"]))
    mc.add("permHi", int(perm["perm_hi"]))
    mc.add("permP", f"{perm['p_ge']:.2f}")
    mc.add("permDscrObserved", perm["by_phase"]["DSCR"]["observed"])
    mc.add("permDscrN", perm["by_phase"]["DSCR"]["n"])
    mc.add("permDscrMean", f1(perm["by_phase"]["DSCR"]["perm_mean"]))
    mc.add("permDscrP", f"{perm['by_phase']['DSCR']['p_ge']:.2f}")


def v4(mc: Macros) -> None:
    b = load("results/lumiere_v4_baselines.json")
    sel = load("data/lumiere/v4/selection_report.json")
    st = load("results/lumiere_v4_stats.json")
    if sel:
        for ph, n in sel["phase_counts"].items():
            mc.add(f"vfourN{ph}", n)
        mc.add("vfourPatients", sel["n_selected"])
        conc = sel["rule_vs_expert_concordance"]
        tot = conc["n"] + sel["n_undetermined_followups"]
        mc.add("vfourFollowups", tot)
        mc.add("vfourUndetermined", sel["n_undetermined_followups"])
        mc.add("vfourConcordant", conc["concordant"])
        mc.add("vfourConcordantPct", f"{100 * conc['concordant'] / tot:.0f}")
        mc.add("vfourSelectedAgree", sel["selected_expert_agrees"])
        for lab, d in conc["by_expert_label"].items():
            short = {"progressive disease": "PD", "stable disease": "SD", "partial response": "PR", "complete response": "CR"}[lab]
            und = sel["undetermined_by_expert"].get(lab, 0)
            mc.add(f"vfourExp{short}N", d["n"] + und)
            mc.add(f"vfourExp{short}Same", d["concordant"])
    if b:
        bp = b["bp_vs_rater"]
        mc.add("vfourBpN", bp["n"])
        mc.add("vfourBpRho", f"{bp['spearman']:.2f}")
        mc.add("vfourBpRatio", f"{bp['median_ratio_ours_over_rater']:.1f}")
        mc.add("vfourPjrfN", b["pjrf"]["n"])
        mc.add("vfourPjrfBase", f"{100 * b['pjrf']['base_rate']:.1f}")
        mc.add("vfourPjrfBrierBase", f"{b['pjrf']['brier_constant_base_rate_loo']:.3f}")
        mc.add("vfourPjrfBrierLR", f"{b['pjrf']['brier_logistic_loo']:.3f}")
        mc.add("vfourPjrfAucLR", f"{b['pjrf']['auc_logistic_loo']:.3f}")
        mc.add("vfourTcmLookupEsc", f1(100 * b["tcm"]["label_only_lookup_escalate"]))
        mc.add("vfourTcmLookupConf", f1(100 * b["tcm"]["label_only_lookup_confirm"]))
        mc.add("vfourTcmPdItems", b["tcm"]["pd_items"])
        for cls, n in b["tcm"]["classes"].items():
            mc.add(f"vfourTcm{cls.capitalize()}", n)
        for ph in ("AIA", "LIL", "DSCR", "TCM"):
            mc.add(f"vfourMajority{ph}", f1(100 * b["keys"][ph]["majority"])) if ph in b["keys"] and "majority" in b["keys"][ph] else None
    # ---- result tables (placeholders until the runs exist)
    OUT.mkdir(parents=True, exist_ok=True)
    mc.add("vfourPending", "1" if not st or not st.get("models") else "0")
    e1, e2, e3, e5 = [], [], [], []
    if st and st.get("models"):
        for m, r in st["models"].items():
            for ph, v in r.get("E1", {}).items():
                e1.append(f"{SHORT.get(m, m)} & {ph} & {v['n']} & {f1(v['acc_a'])} & {f1(v['acc_b'])} & "
                          f"{signed(v['diff'])} [{signed(v['ci'][0])}, {signed(v['ci'][1])}] & {v['verdict'].replace('+/-', '$\\pm$').replace('pp', ' pp')} \\\\")
            for ph, v in r.get("E2", {}).items():
                e2.append(f"{SHORT.get(m, m)} & {ph} & {v['n']} & {f1(v['own_image_correct'])} & {f1(v['swap_answers_donor_key'])} & "
                          f"{f1(v['text_answers_donor_key'])} & {signed(v['gain'])} [{signed(v['gain_ci'][0])}, {signed(v['gain_ci'][1])}] \\\\")
            e = r.get("E3", {})
            g = e.get("ctx_gold", {})
            fw = e.get("flip_window", {})
            pdw = fw.get("progressive_disease_items")
            e3.append(f"{SHORT.get(m, m)} & {f1(g['acc']) if g else '--'} & {f1(e['ctx_wrong']['acc']) if 'ctx_wrong' in e else '--'} & "
                      f"{f1(e['ctx_absent']['acc']) if 'ctx_absent' in e else '--'} & "
                      f"{f1(e['flip_label']['follows_rule_after_flip']) if 'flip_label' in e else '--'} & "
                      f"{f1(pdw['follows']) if pdw else '--'} \\\\")
            for cond, v in r.get("E5", {}).items():
                if cond == "ctx_gold":
                    e5.append(f"{SHORT.get(m, m)} & {v['n']} & {v['brier']:.3f} & {v['brier_base_rate_loo']:.3f} & {v['skill']:+.3f} & {v['auc']:.2f} \\\\")
    else:
        for m in MODELS:
            e1.append(f"{SHORT[m]} & AIA / LIL / DSCR & -- & -- & -- & -- & -- \\\\")
            e2.append(f"{SHORT[m]} & AIA / LIL / DSCR & -- & -- & -- & -- & -- \\\\")
            e3.append(f"{SHORT[m]} & -- & -- & -- & -- & -- \\\\")
            e5.append(f"{SHORT[m]} & -- & -- & -- & -- & -- \\\\")
    heads = {
        "e1": ("llrrrll", ["Model & Phase & $n$ & Image & Text-only & $\\Delta$ [95\\% CI] & Verdict \\\\"]),
        "e2": ("llrrrrl", ["Model & Phase & $n$ & Own image & Swap: donor key & Text: donor key & Gain [95\\% CI] \\\\"]),
        "e3": ("lccccc", [" & \\multicolumn{3}{c}{TCM acc.\\ (\\%)} & \\multicolumn{2}{c}{Follows rule (\\%)} \\\\",
                         "\\cmidrule(lr){2-4}\\cmidrule(lr){5-6}", " & true & wrong & none & label & timing (PD) \\\\"]),
        "e5": ("lccccc", ["Model & $n$ & Brier & Base rate & Skill & AUC \\\\"]),
    }
    for name, rows in (("e1", e1), ("e2", e2), ("e3", e3), ("e5", e5)):
        cs, hd = heads[name]
        (OUT / f"tab_v4_{name}.tex").write_text(tabular(cs, hd, rows))


def check_stale() -> list[str]:
    tex = Path("paper/latex/acl_latex.tex").read_text()
    return [pat for pat in STALE if re.search(pat, tex)]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    mc = Macros()
    cohort(mc)
    v3_tables(mc)
    v4(mc)
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "numbers.tex").write_text(mc.tex())
    (OUT / "numbers.json").write_text(json.dumps(mc.d, indent=1, sort_keys=True))
    print(f"wrote {len(mc.d)} macros and tables to {OUT}")
    if args.check:
        bad = check_stale()
        if bad:
            raise SystemExit(f"stale numbers still in acl_latex.tex: {bad}")
        print("no stale numbers found")


if __name__ == "__main__":
    main()
