"""
One authoritative source for every number the paper quotes (paper/review.md, concern 5).

Reads the raw data and the result files and writes, under paper/latex/generated/:
  numbers.tex        \\newcommand macros for every scalar the text cites (v3 audit and v4)
  tab_v3_*.tex       the v3 tables (text-only, options-only, gating-causality)
  tab_v4_*.tex       the v4 tables (baselines, E1-E5); cells read "--" until the v4 runs exist
  numbers.json       the same scalars, for checking

Nothing here is typed by hand: the paper cites macros and \\input's tables. Run after any change to the results:
  python -m tools.paper_numbers            # regenerate
  python -m tools.paper_numbers --check    # also fail if the .tex still contains a known stale number
"""

from __future__ import annotations

import argparse
import glob
import json
import re
from collections import Counter
from math import comb
from pathlib import Path

import numpy as np

import config.lumiere as lcfg
from src.lumiere_labels import canonical_answer_text

OUT = Path("paper/latex/generated")
MODELS = ["MedGemma-4B", "Gemma-3-12B", "Gemma-3-27B", "Llama-4-Scout"]
TAG = {"Gemini-3.6-Flash": "Gemini", "Gemma-3-27B-bf16": "GemmaTwentySevenBf", "Pixtral-12B-bf16": "Pixtral", "MedGemma-4B": "MedGemma", "Gemma-3-12B": "GemmaTwelve", "Gemma-3-27B": "GemmaTwentySeven", "Llama-4-Scout": "Scout"}
SHORT = {"Gemini-3.6-Flash": "Gemini-3.6-Flash", "Gemma-3-27B-bf16": "Gemma-3-27B (bf16)", "Pixtral-12B-bf16": "Pixtral-12B", "MedGemma-4B": "MedGemma-4B", "Gemma-3-12B": "Gemma-3-12B", "Gemma-3-27B": "Gemma-3-27B", "Llama-4-Scout": "Llama-4-Scout"}
PHASES = ["AIA", "LIL", "DSCR", "PJRF", "TCM"]
STALE = [r"63\.5", r"33 of 33", r"(?<!which gave )50 of 52", r"48 and 52", r"33 progressive", r"14\\%\)"]   # figures that came from the label-spelling bug or typos


def load(p: str):
    fp = Path(p)
    return json.loads(fp.read_text()) if fp.exists() else None


def binom_sf(k: int, n: int, p: float) -> float:
    """P(X >= k), X ~ Binomial(n, p)."""
    return sum(comb(n, i) * p ** i * (1 - p) ** (n - i) for i in range(k, n + 1))


def f1(x: float) -> str:
    return f"{x:.1f}"


def signed(x: float) -> str:
    return f"{x:+.1f}".replace("-", "$-$")


def pfmt(p: float) -> str:
    return "$<$.001" if p < 0.001 else f"{p:.3f}".lstrip("0") if p < 1 else "1.00"


# phase chips (macros defined in acl_latex.tex preamble); keep the look consistent across tables
PTAG = {"AIA": "\\ptagAIA", "LIL": "\\ptagLIL", "DSCR": "\\ptagDSCR"}


def _carries_color(row: str) -> bool:
    return row.lstrip().startswith(("\\rowcolor", "\\hirow", "\\bandrow", "\\hdrrow"))


def tabular(colspec: str, header: list[str], rows: list[str], size: str = "", zebra: bool = True) -> str:
    """A complete tabular (an \\input inside a tabular breaks booktabs rules, so the whole environment is generated).

    Shades the header row(s) and, when ``zebra``, bands alternate body rows. Rows that already
    carry their own ``\\rowcolor`` (e.g. a highlighted key row) are left untouched.
    """
    hdr = [h if (h.strip().startswith("\\cmidrule") or "&" not in h or _carries_color(h))
           else "\\hdrrow " + h for h in header]
    body, bi = [], 0
    for r in rows:
        if _carries_color(r):
            body.append(r)
        else:
            body.append(("\\bandrow " + r) if (zebra and bi % 2 == 1) else r)
            bi += 1
    return (f"{size}\\begin{{tabular}}{{{colspec}}}\n\\toprule\n" + "\n".join(hdr) + "\n\\midrule\n"
            + "\n".join(body) + "\n\\bottomrule\n\\end{tabular}\n")


class Macros:
    def __init__(self):
        self.d: dict[str, str] = {}

    def add(self, name: str, value) -> None:
        assert re.fullmatch(r"[A-Za-z]+", name), f"macro names are letters only: {name}"
        self.d[name] = str(value)

    def tex(self) -> str:
        return "% generated by tools/paper_numbers.py; do not edit\n" + "\n".join(
            f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in sorted(self.d.items())) + "\n"


def cohort(mc: Macros) -> None:
    for tag, d in (("Fifty", "data/lumiere/facts"), ("Vthree", "data/lumiere/v3/facts")):
        ps = sorted(Path(d).glob("Patient-*.json"))
        cnt = Counter(json.loads(p.read_text())["phase_facts"]["DSCR"]["rating_code"] for p in ps)
        mc.add(f"nPat{tag}", len(ps))
        for code, name in (("PD", "PD"), ("SD", "SD"), ("PR", "PR"), ("CR", "CR")):
            mc.add(f"dscr{tag}{name}", cnt[code])
    n3 = int(mc.d["nPatVthree"])
    mc.add("dscrMajorityCount", mc.d["dscrVthreePD"])
    mc.add("dscrMajorityPct", f1(100 * int(mc.d["dscrVthreePD"]) / n3))
    mc.add("nPatAll", 91)
    mc.add("nPatEligible", 55)


def v3_tables(mc: Macros) -> None:
    rv = load("results/lumiere_reviewer_stats.json")
    gs = load("results/lumiere_gating_stats.json")
    tl = load("results/lumiere_tcm_lookup.json")
    OUT.mkdir(parents=True, exist_ok=True)
    maj = int(mc.d["dscrVthreePD"]) / int(mc.d["nPatVthree"])
    # text-only accuracy table
    rows = []
    for m in ["Llama-4-Scout", "Gemma-3-27B", "Gemma-3-12B", "MedGemma-4B"]:
        a = rv["accuracy"][m]
        rows.append(f"{SHORT[m]} & {f1(100 * a['acc_img'])} & {f1(100 * a['acc_txt'])} & "
                    f"{signed(100 * a['diff'])} [{signed(100 * a['ci'][0])}, {signed(100 * a['ci'][1])}] \\\\")
        mc.add(f"vthreeDiff{TAG[m]}", signed(100 * a["diff"]))
    (OUT / "tab_v3_textonly.tex").write_text(tabular("lccc", ["Model & Image & Text-only & $\\Delta$ [95\\% CI] \\\\"], rows))
    # DSCR accuracy against the majority rate
    for m in MODELS:
        o = gs["options"][m]["phases"]["DSCR"]
        k = round(o["acc_own_image"] * 52)
        tag = TAG[m]
        mc.add(f"vthreeDscrAcc{tag}", f1(100 * o["acc_own_image"]))
        mc.add(f"vthreeDscrP{tag}", f"{binom_sf(k, 52, maj):.2f}")
    # options-only table
    rows = []
    for m in MODELS:
        for i, ph in enumerate(PHASES):
            o = gs["options"][m]["phases"][ph]
            dag = "$^\\dagger$" if o.get("flagged_parse_errors") else ""
            rows.append(f"{SHORT[m] if i == 0 else ''} & {ph} & {f1(100 * o['acc_options_only'])}{dag} & {f1(100 * o['acc_no_chain'])} & "
                        f"{f1(100 * o['acc_own_image'])} & {o['parse_errors']} \\\\")
    (OUT / "tab_v3_optonly.tex").write_text(tabular("llcccc", ["Model & Phase & Opt.-only & No chain & Own-img & Unpars. \\\\"], rows, "\\scriptsize\n"))
    # gating table: c / w / a for TCM and DSCR, ablation deltas
    rows = []
    for m in MODELS:
        t = gs["gating"][m]["phases"]["TCM"]["acc"]
        d = gs["gating"][m]["phases"]["DSCR"]["acc"]
        ab = gs["ablation"][m]
        star = lambda c: "$^{*}$" if c["ci"][0] > 0 or c["ci"][1] < 0 else ""
        di, de = ab["incl-DSCR"]["correct-incorrect"], ab["excl-DSCR"]["correct-incorrect"]
        rows.append(f"{SHORT[m]} & {round(100 * t['correct'])}/{round(100 * t['incorrect'])}/{round(100 * t['absent'])} & "
                    f"{signed(100 * di['diff'])}{star(di)} & {signed(100 * de['diff'])}{star(de)} & "
                    f"{round(100 * d['correct'])}/{round(100 * d['incorrect'])}/{round(100 * d['absent'])} \\\\")
        tag = TAG[m]
        full = gs["gating"][m]["phases"]["TCM"]["contrasts"]["correct-incorrect"]
        mc.add(f"vthreeTcmGap{tag}", f1(100 * full["diff"]))
        mc.add(f"vthreeTcmGapP{tag}", f"{full['mcnemar_p']:.3f}")
        mc.add(f"vthreeTcmDscrOnly{tag}", signed(100 * di["diff"]))
        mc.add(f"vthreeTcmNoDscr{tag}", signed(100 * de["diff"]))
        dc = gs["gating"][m]["phases"]["DSCR"]["contrasts"]["correct-absent"]
        mc.add(f"vthreeDscrCtxHurt{tag}", signed(100 * dc["diff"]))
        mc.add(f"vthreeDscrCtxHurtP{tag}", f"{dc['mcnemar_p']:.3f}")
    (OUT / "tab_v3_gating.tex").write_text(tabular("lcccc", [" & \\multicolumn{3}{c}{TCM} & DSCR \\\\", "\\cmidrule(lr){2-4}\\cmidrule(lr){5-5}",
        "Model & c / w / a & $\\Delta_{\\text{DSCR}}$ & $\\Delta_{\\text{no DSCR}}$ & c / w / a \\\\"], rows))
    # TCM label lookup
    k = tl["key"]
    for name, val in (("tcmAgree", k["agree"]), ("tcmN", k["n"]), ("tcmPdN", k["pd_n"]), ("tcmPdEsc", k["pd_escalate"]),
                      ("tcmNonN", k["nonpd_n"]), ("tcmNonCont", k["nonpd_continue"]), ("tcmClassUnique", k["class_unique"])):
        mc.add(name, val)
    for m in MODELS:
        tag = TAG[m]
        f = tl["follow"][m]
        for cond in ("correct", "incorrect", "absent"):
            v = f[cond]
            mc.add(f"tcmFollow{cond.capitalize()}{tag}", v if isinstance(v, (int, str)) else v.get("escalate", v))
    # donor test
    perm = rv["counterfactual"]["pooled"]["donor_permutation"]
    mc.add("permObserved", perm["observed"])
    mc.add("permN", perm["n"])
    mc.add("permMean", f1(perm["perm_mean"]))
    mc.add("permLo", int(perm["perm_lo"]))
    mc.add("permHi", int(perm["perm_hi"]))
    mc.add("permP", f"{perm['p_ge']:.2f}")
    mc.add("permDscrObserved", perm["by_phase"]["DSCR"]["observed"])
    mc.add("permDscrN", perm["by_phase"]["DSCR"]["n"])
    mc.add("permDscrMean", f1(perm["by_phase"]["DSCR"]["perm_mean"]))
    mc.add("permDscrP", f"{perm['by_phase']['DSCR']['p_ge']:.2f}")


def rng(mc: Macros, name: str, vals, fmt=lambda x: f"{x:.0f}") -> None:
    """<name>Lo and <name>Hi macros: the range endpoints of a per-model quantity."""
    mc.add(f"{name}Lo", fmt(min(vals)))
    mc.add(f"{name}Hi", fmt(max(vals)))


def v3_appendix(mc: Macros) -> None:
    """Range and count macros for the v3 appendix prose (text-only agreement, repeats, evidence audit, flips, options-only)."""
    import csv
    rv = load("results/lumiere_reviewer_stats.json")
    gs = load("results/lumiere_gating_stats.json")
    cf = load("results/lumiere_counterfactual_summary.json")
    M4 = ["MedGemma-4B", "Gemma-3-12B", "Gemma-3-27B", "Llama-4-Scout"]
    mc.add("vthreeMaxAbsDiff", f1(max(abs(100 * rv["accuracy"][m]["diff"]) for m in M4)))
    # answers identical with and without the image (non-gated v3 run vs its text-only twin)
    same = []
    for m in M4:
        a, b = (sorted(glob.glob(f"results/lumiere_{m}{t}_v3_nogate_*"))[-1] for t in ("", "_textonly"))
        ans = lambda d: {(c["case_id"], ph): v["questions"][0].get("model_answer") for c in json.loads(Path(d, "raw_results.json").read_text())
                         for ph, v in c["phases"].items() if v.get("questions")}
        x, y = ans(a), ans(b)
        ks = [k for k in x if k in y]
        same.append(100 * sum(x[k] == y[k] for k in ks) / len(ks))
    rng(mc, "vthreeSame", same)
    rep = gs["repeat"]
    mc.add("vthreeRepeatN", rep[M4[0]]["n"])
    mc.add("vthreeRepeatIdentical", min(rep[m]["identical_answer"] for m in M4))
    assert all(rep[m]["identical_answer"] == rep[m]["n"] for m in M4), "repeat runs are no longer identical; reword the appendix"
    # flip rates between own and donor image
    for ph in ("AIA", "LIL", "DSCR"):
        rng(mc, f"vthreeFlip{ph}", [100 * cf[m]["per_phase"][ph]["flipped"] / cf[m]["per_phase"][ph]["n"] for m in M4])
    perm = rv["counterfactual"]["pooled"]["donor_permutation"]
    mc.add("permObservedPct", f1(100 * perm["observed"] / perm["n"]))
    # evidence audit, non-gated v3 runs: availability x record status; "contradict" = contradicted or matching no fact value
    rows = list(csv.DictReader(open("results/lumiere_reasoning_facts.csv")))
    per = {k: [] for k in ("noclaim", "claims", "inok", "inbad", "newok", "newbad")}
    for m in M4:
        rs = [r for r in rows if r["model"] == f"{m}_v3"]
        cell = lambda a, b: sum(int(r[f"cell_{a}|{b}"]) for r in rs)
        tot = sum(int(v) for r in rs for k, v in r.items() if k.startswith("cell_"))
        per["noclaim"].append(100 * sum(r["label"] == "no_claims" for r in rs) / len(rs))
        per["claims"].append(tot)
        per["inok"].append(100 * cell("in_text", "supported") / tot)
        per["inbad"].append(100 * (cell("in_text", "contradicted") + cell("in_text", "unmatched")) / tot)
        per["newok"].append(100 * cell("not_in_text", "supported") / tot)
        per["newbad"].append(100 * (cell("not_in_text", "contradicted") + cell("not_in_text", "unmatched")) / tot)
    for k, name in (("noclaim", "Noclaim"), ("claims", "Claims"), ("inok", "InOk"), ("inbad", "InBad"), ("newok", "NewOk"), ("newbad", "NewBad")):
        rng(mc, f"vthreeEv{name}", per[k])
    # options-only: cells with many unparseable responses are excluded from the range (the appendix says they are not interpreted)
    for ph in PHASES:
        keep = [100 * gs["options"][m]["phases"][ph]["acc_options_only"] for m in M4 if not gs["options"][m]["phases"][ph].get("flagged_parse_errors")]
        rng(mc, f"vthreeOpt{ph}", keep)
    bad = [100 * gs["options"]["MedGemma-4B"]["phases"][ph]["parse_errors"] / gs["options"]["MedGemma-4B"]["phases"][ph]["n"]
           for ph in PHASES if gs["options"]["MedGemma-4B"]["phases"][ph].get("flagged_parse_errors")]
    mc.add("vthreeMedGemmaUnparsedN", len(bad))
    rng(mc, "vthreeMedGemmaUnparsed", bad)
    # option-only heuristics on the v3 items
    bl = rv["baselines"]
    for ph in ("AIA", "LIL", "DSCR", "PJRF", "TCM"):
        mc.add(f"vthreeLongest{ph}", f"{100 * bl[ph]['longest'] / bl[ph]['n']:.0f}")
    rng(mc, "vthreeLetterPrior", [100 * bl[ph]["letter_prior"] / bl[ph]["n"] for ph in bl])


def _moved(sm: dict, key: str) -> str:
    """'moved / informative' (items whose answer moved to the rule's new answer, over items whose original answer was not already it)."""
    v = sm.get("transitions", {}).get(key)
    return f"{v['moved_to_new']}/{v['informative_n']}" if v else "--"


def v4_supplement(mc: Macros) -> None:
    """Macros and tables from results/lumiere_v4_supplement.json (descriptive, added after the runs)."""
    sp = load("results/lumiere_v4_supplement.json")
    if not sp:
        return
    a = sp["audit"]
    mc.add("vfourDeterminate", a["determinate"])
    mc.add("vfourConcordantDetPct", f"{a['pct_of_determinate']:.0f}")
    mc.add("vfourConcordantDetLo", f"{a['wilson_determinate'][0]:.0f}")
    mc.add("vfourConcordantDetHi", f"{a['wilson_determinate'][1]:.0f}")
    sr = json.loads(Path("data/lumiere/v4/selection_report.json").read_text())      # dataset summary
    mc.add("vfourCandPatients", sr["n_patients_with_first_line_candidates"])
    for key, nm in (("t1", "TOne"), ("ct1", "TOneC"), ("t2", "TTwo"), ("flair", "Flair")):
        mc.add(f"vfourAiaCount{nm}", sr["aia_sequence_counts"][key])
    for lab, nm in (("Left hemisphere, posterior half", "LP"), ("Right hemisphere, posterior half", "RP"),
                    ("Right hemisphere, anterior half", "RA"), ("Left hemisphere, anterior half", "LA")):
        mc.add(f"vfourLilCount{nm}", sr["lil_key_counts"][lab])
    for lab, nm in (("Complete response", "CR"), ("Progressive disease", "PD"), ("Partial response", "PR"), ("Stable disease", "SD")):
        mc.add(f"vfourDscrCount{nm}", sr["dscr_key_counts"][lab])
    for ph in ("AIA", "LIL", "DSCR"):
        mc.add(f"vfourPairs{ph}", sr["pairs_built"][ph])
    mc.add("vfourSelExpertAgrees", sr["selected_expert_agrees"])
    ac = sp.get("audit_clustered")
    if ac:
        mc.add("vfourAuditPatients", ac["patients"])
        mc.add("vfourAuditPerPatientMax", ac["followups_by_patient_max"])
        mc.add("vfourAuditClusterLo", f"{ac['cluster_ci_determinate'][0]:.0f}")
        mc.add("vfourAuditClusterHi", f"{ac['cluster_ci_determinate'][1]:.0f}")
        mc.add("vfourAuditClusterAllLo", f"{ac['cluster_ci_all'][0]:.0f}")
        mc.add("vfourAuditClusterAllHi", f"{ac['cluster_ci_all'][1]:.0f}")
    mc.add("vfourDisagree", a["disagreements"])
    for lab, short in (("complete response", "CR"), ("progressive disease", "PD"), ("stable disease", "SD"), ("partial response", "PR")):
        mc.add(f"vfourDisRule{short}", a["disagreements_by_rule_label"].get(lab, 0))
    conf = a["confusion_expert_by_rule"]
    mc.add("vfourConfSDasPD", conf.get("stable disease|progressive disease", 0))
    mc.add("vfourConfPDasCR", conf.get("progressive disease|complete response", 0))
    mc.add("vfourConfSDasCR", conf.get("stable disease|complete response", 0))
    nl = sp.get("audit_new_lesion")
    if nl:
        mc.add("vfourNewLesionN", nl["n"])
        mc.add("vfourNewLesionPlausible", nl.get("plausible_new_lesion", 0))
        mc.add("vfourNewLesionNone", nl.get("no_distinct_measurable_component_elsewhere", 0))
        mc.add("vfourNewLesionPreexisting", nl.get("preexisting_secondary_lesion", 0))
    rows_h, rows_t = [], []
    for m, r in sp["models"].items():
        t = TAG[m]
        h = r["handling"]
        er = r.get("explicit_rule")
        if er:
            mc.add(f"vfourExplGold{t}", f"{er['acc_gold']:.1f}")
            mc.add(f"vfourExplAcc{t}", f"{er['acc_explicit']:.1f}")
            mc.add(f"vfourExplDiff{t}", signed(er["diff"]))
            mc.add(f"vfourExplLo{t}", signed(er["diff_ci"][0]))
            mc.add(f"vfourExplHi{t}", signed(er["diff_ci"][1]))
            mc.add(f"vfourExplParseGold{t}", er["parse_error_gold"])
            mc.add(f"vfourExplParse{t}", er["parse_error_explicit"])
        mc.add(f"vfourParseInvalid{t}", h["ALL"]["parse_error"])
        mc.add(f"vfourParseNoLetter{t}", h["ALL"]["no_answer"])
        mc.add(f"vfourParseN{t}", h["ALL"]["n"])
        dv = r.get("dscr_valid_json")
        if dv:
            mc.add(f"vfourDscrAccAll{t}", f1(dv["acc_all"]))
            mc.add(f"vfourDscrAccValid{t}", f1(dv["acc_valid"]))
        for ph, v in r["outcomes"].items():
            mc.add(f"vfourSensOwnText{ph}{t}", f1(v["own_vs_text_answer_differs"]))
            mc.add(f"vfourSensSwap{ph}{t}", f1(v["swap_vs_own_answer_differs"]))
        rows_h.append(f"{SHORT.get(m, m)} & {h['ALL']['n']} & {h['ALL']['parse_error']} & {h['ALL']['no_answer']} \\\\")
        for k, v in r.get("transitions", {}).items():
            cond, sub = k.split("|")
            if (cond, sub) not in (("flip_label", "all"), ("flip_window", "pd")):
                continue
            nm = "Label" if cond == "flip_label" else "Timing"
            mc.add(f"vfourTrans{nm}Moved{t}", v["moved_to_new"])
            mc.add(f"vfourTrans{nm}Already{t}", v["already_at_new"])
            mc.add(f"vfourTrans{nm}Inf{t}", v["informative_n"])
            mc.add(f"vfourTrans{nm}N{t}", v["n"])
            mc.add(f"vfourTrans{nm}Pct{t}", f"{v['moved_of_informative']:.0f}")
            rows_t.append(f"{SHORT.get(m, m)} & {'label (all)' if cond == 'flip_label' else 'timing (PD)'} & {v['n']} & {v['moved_to_new']} & {v['already_at_new']} & "
                          f"{v['unchanged_elsewhere']} & {v['changed_to_other']} & {v['moved_to_new']}/{v['informative_n']} & "
                          f"{f1(100 * (v['moved_to_new'] + v['already_at_new']) / v['n'])} \\\\")
        p = r.get("pjrf")
        if p:
            mc.add(f"vfourEfiveDiff{t}", f"{p['diff_to_base']:+.3f}".replace("-", "$-$"))
            mc.add(f"vfourEfiveDiffLo{t}", f"{p['diff_ci'][0]:+.3f}".replace("-", "$-$"))
            mc.add(f"vfourEfiveDiffHi{t}", f"{p['diff_ci'][1]:+.3f}".replace("-", "$-$"))
            mc.add(f"vfourEfiveNoForecast{t}", p["no_forecast"])
    z = sp["audit_size"]
    k = z["ratio_0.67_1.5"]
    mc.add("vfourSizeN", z["n"])
    mc.add("vfourSizeExpertPD", z["expert_counts"].get("progressive disease", 0))
    mc.add("vfourSizeCloseAgree", k["close_agree"])
    mc.add("vfourSizeCloseN", k["close_n"])
    mc.add("vfourSizeOtherAgree", k["other_agree"])
    mc.add("vfourSizeOtherN", k["other_n"])
    o = sp["pjrf_origin"]
    mc.add("vfourPjrfOsN", o["with_survival"])
    mc.add("vfourPjrfOsNA", o["without_survival"])
    mc.add("vfourPjrfOsShort", o["survival_before_last_imaging"])
    mc.add("vfourPjrfOsShortCohort", len(o["in_v4_cohort"]))
    mc.add("vfourPjrfFlipFour", o["labels_that_flip_under_origin_shift"]["4"])
    mc.add("vfourPjrfFlipEight", o["labels_that_flip_under_origin_shift"]["8"])
    aia = sp["aia"]
    mc.add("vfourRefErrAIA", sum(e["phase"] == "AIA" for e in aia["reference_errors"]))
    mc.add("vfourRefErrLIL", sum(e["phase"] == "LIL" for e in aia["reference_errors"]))
    shares = [aia["modal_answer_share"][m]["share"] for m in MODELS if m in aia["modal_answer_share"]]
    rng(mc, "vfourAiaModalShare", shares)
    for ph in ("AIA", "LIL", "DSCR"):
        for key, nm in (("own_vs_text_answer_differs", "OwnText"), ("swap_vs_own_answer_differs", "Swap")):
            vals = [sp["models"][m]["outcomes"][ph][key] for m in MODELS if m in sp["models"] and ph in sp["models"][m]["outcomes"]]
            if vals:
                rng(mc, f"vfourSensRange{nm}{ph}", vals)
    (OUT / "tab_v4_e3trans.tex").write_text(tabular("llrrrrrrr", ["Model & Flip & Items & Moved & Already there & Unchanged & Other & Moved / informative & Registered share (\\%) \\\\"], rows_t))
    (OUT / "tab_v4_handling.tex").write_text(tabular("lrrr", ["Model & Records & Invalid JSON & No answer letter \\\\"], rows_h))


def v4_inputcheck(mc: Macros) -> None:
    """Macros and a table from the latest results/lumiere_v4_inputcheck_<model>_* report of each pipeline (tools/lumiere_v4_input_check.py)."""
    rows = []
    for m in MODELS + ["Gemma-3-27B-bf16"]:
        reps = sorted(glob.glob(f"results/lumiere_v4_inputcheck_{m}_2*"))
        rep = load(f"{reps[-1]}/report.json") if reps else None
        if not rep:
            continue
        t = TAG[m]
        incs = [i for v in rep["tokens"]["phases"].values() for i in v["increment_per_added_image"] if i is not None]
        text_only = [v["text_only_tokens"] for v in rep["tokens"]["phases"].values()]
        passed = sum(p["pass"] for p in rep["probes"])
        mc.add(f"vfourIcTokMin{t}", min(incs))
        mc.add(f"vfourIcTokMax{t}", max(incs))
        mc.add(f"vfourIcTokMean{t}", f"{sum(incs) / len(incs):.0f}")
        mc.add(f"vfourIcTextOnly{t}", f"{sum(text_only) / len(text_only):.0f}")
        mc.add(f"vfourIcProbePass{t}", passed)
        mc.add(f"vfourIcProbeN{t}", len(rep["probes"]))
        sv = rep.get("serving", {})
        det = sv.get("details") or {}
        lst = sv.get("listing") or {}
        digest = (lst.get("digest") or "")[:12]
        if sv.get("backend") == "vllm":       # vLLM serves the Hugging Face weights unquantized: no digest, dtype fixed by the serve command
            det = {"quantization_level": "bf16 (vLLM)"}
        if det.get("parameter_size"):
            mc.add(f"vfourParams{t}", str(det["parameter_size"]).replace("B", ""))
        rows.append(f"{SHORT.get(m, m)} & {sv.get('model_tag', '')} & {digest or '--'} & {str(det.get('quantization_level', '--')).replace('_', chr(92) + '_')} & "
                    f"{min(incs)}--{max(incs)} & {passed}/{len(rep['probes'])} \\\\")
    cb = load("results/compute_budget.json")
    if cb:
        mc.add("vfourGpuHoursAll", f"{cb['gpu_hours_all']:.0f}")
        mc.add("vfourGpuHoursVfour", f"{cb['gpu_hours_v4_family']:.0f}")
        mc.add("vfourApiCalls", cb["gemini_api"]["calls"])
        mc.add("vfourApiTokensM", f"{cb['gemini_api']['total_tokens'] / 1e6:.1f}")
    if rows:
        (OUT / "tab_v4_inputcheck.tex").write_text(tabular("llllrr", ["Model & Tag & Digest & Quantization & Tokens per image & Probes passed \\\\"], rows))


def v4(mc: Macros) -> None:
    b = load("results/lumiere_v4_baselines.json")
    sel = load("data/lumiere/v4/selection_report.json")
    st = load("results/lumiere_v4_stats.json")
    sup = (load("results/lumiere_v4_supplement.json") or {}).get("models", {})   # post-review descriptive supplement
    # Pixtral-12B-bf16 (second precision/stack control): its DSCR image conditions returned empty output on the 3-image
    # prompt and are excluded; these counts back the exclusion note in the results and appendix.
    _pix = sorted(glob.glob("results/lumiere_v4_Pixtral-12B-bf16_image_*"))
    if _pix:
        _er = load(str(Path(_pix[-1]) / "empty_responses.json")) or []
        _ps = load(str(Path(_pix[-1]) / "summary.json")) or {}
        _dscr = [e for e in _er if e[1] == "DSCR"]
        mc.add("vfourPixtralDscrEmptyOwn", sum(1 for e in _dscr if e[2] == "own"))
        mc.add("vfourPixtralDscrEmptySwap", sum(1 for e in _dscr if e[2] == "swap"))
        mc.add("vfourPixtralDscrSwapN", _ps.get("DSCR", {}).get("swap", {}).get("n", ""))
    if sel:
        for ph, n in sel["phase_counts"].items():
            mc.add(f"vfourN{ph}", n)
        mc.add("vfourPatients", sel["n_selected"])
        conc = sel["rule_vs_expert_concordance"]
        tot = conc["n"] + sel["n_undetermined_followups"]
        mc.add("vfourFollowups", tot)
        mc.add("vfourUndetermined", sel["n_undetermined_followups"])
        mc.add("vfourConcordant", conc["concordant"])
        mc.add("vfourConcordantPct", f"{100 * conc['concordant'] / tot:.0f}")
        mc.add("vfourSelectedAgree", sel["selected_expert_agrees"])
        for lab, d in conc["by_expert_label"].items():
            short = {"progressive disease": "PD", "stable disease": "SD", "partial response": "PR", "complete response": "CR"}[lab]
            und = sel["undetermined_by_expert"].get(lab, 0)
            mc.add(f"vfourExp{short}N", d["n"] + und)
            mc.add(f"vfourExp{short}Same", d["concordant"])
    if b:
        bp = b["bp_vs_rater"]
        mc.add("vfourBpN", bp["n"])
        mc.add("vfourBpRho", f"{bp['spearman']:.2f}")
        mc.add("vfourBpRatio", f"{bp['median_ratio_ours_over_rater']:.1f}")
        mc.add("vfourPjrfN", b["pjrf"]["n"])
        mc.add("vfourPjrfBase", f"{100 * b['pjrf']['base_rate']:.1f}")
        mc.add("vfourPjrfBrierBase", f"{b['pjrf']['brier_constant_base_rate_loo']:.3f}")
        mc.add("vfourPjrfBrierLR", f"{b['pjrf']['brier_logistic_loo']:.3f}")
        mc.add("vfourPjrfAucLR", f"{b['pjrf']['auc_logistic_loo']:.3f}")
        mc.add("vfourTcmLookupEsc", f1(100 * b["tcm"]["label_only_lookup_escalate"]))
        mc.add("vfourTcmLookupConf", f1(100 * b["tcm"]["label_only_lookup_confirm"]))
        mc.add("vfourTcmPdItems", b["tcm"]["pd_items"])
        for cls, n in b["tcm"]["classes"].items():
            mc.add(f"vfourTcm{cls.capitalize()}", n)
        for ph in ("AIA", "LIL", "DSCR", "TCM"):
            mc.add(f"vfourMajority{ph}", f1(100 * b["keys"][ph]["majority"])) if ph in b["keys"] and "majority" in b["keys"][ph] else None
    # ---- result tables (placeholders until the runs exist)
    OUT.mkdir(parents=True, exist_ok=True)
    mc.add("vfourPending", "1" if not st or not st.get("models") else "0")
    e1, e2, e3, e5 = [], [], [], []
    def _interval(verdict: str) -> str:
        t = verdict.strip()
        if t == "CI above 0":
            return "\\ivok"
        if t == "inconclusive":
            return "\\ivinc"
        if t.startswith("within"):
            return "\\ivmargin"
        return verdict
    if st and st.get("models"):
        for mi, (m, r) in enumerate(st["models"].items()):
            for ph, v in r.get("E1", {}).items():
                differ = sup.get(m, {}).get("outcomes", {}).get(ph, {}).get("own_vs_text_answer_differs")
                verdict_tex = v['verdict'].replace('image helps', 'CI above 0').replace('+/-', '$\\pm$').replace('pp', ' pp')
                survives = v.get('p_holm') is not None and v['p_holm'] < 0.05
                dcell = f"{signed(v['diff'])} [{signed(v['ci'][0])}, {signed(v['ci'][1])}]"
                if survives:
                    prefix, dcell = "\\hirow ", f"\\textbf{{{dcell}}}"
                elif mi % 2 == 1:
                    prefix = "\\bandrow "
                else:
                    prefix = ""
                e1.append(f"{prefix}{SHORT.get(m, m)} & {PTAG.get(ph, ph)} & {v['n']} & {f1(v['acc_a'])} & {f1(v['acc_b'])} & "
                          f"{dcell} & [{signed(v['ci_sparse'][0])}, {signed(v['ci_sparse'][1])}] & {pfmt(v['p'])} & "
                          f"{f1(differ) if differ is not None else '--'} & {_interval(verdict_tex)} \\\\")
            for ph, v in r.get("E2", {}).items():
                e2.append(f"{SHORT.get(m, m)} & {PTAG.get(ph, ph)} & {v['n']} & {f1(v['own_image_correct'])} & {f1(v['swap_answers_donor_key'])} & "
                          f"{f1(v['text_answers_donor_key'])} & {signed(v['gain'])} [{signed(v['gain_ci'][0])}, {signed(v['gain_ci'][1])}] & "
                          f"[{signed(v['gain_ci_sparse'][0])}, {signed(v['gain_ci_sparse'][1])}] & {pfmt(v['gain_p'])} & {f1(v['swap_flips_answer_vs_own'])} \\\\")
            e = r.get("E3", {})
            g = e.get("ctx_gold", {})
            fw = e.get("flip_window", {})
            pdw = fw.get("progressive_disease_items")
            e3.append(f"{SHORT.get(m, m)} & {f1(g['acc']) if g else '--'} & {f1(e['ctx_wrong']['acc']) if 'ctx_wrong' in e else '--'} & "
                      f"{f1(e['ctx_absent']['acc']) if 'ctx_absent' in e else '--'} & "
                      f"{_moved(sup.get(m, {}), 'flip_label|all')} & {_moved(sup.get(m, {}), 'flip_window|pd')} \\\\")
            for cond, v in r.get("E5", {}).items():
                if cond == "ctx_gold":
                    pj = sup.get(m, {}).get("pjrf")
                    dtx = f"{pj['diff_to_base']:+.3f} [{pj['diff_ci'][0]:+.3f}, {pj['diff_ci'][1]:+.3f}]".replace("-", "$-$") if pj else "--"
                    e5.append(f"{SHORT.get(m, m)} & {v['n']} & {v['brier']:.3f} & {v['brier_base_rate_loo']:.3f} & {v['skill']:+.3f} & {dtx} & {v['auc']:.2f} \\\\")
    else:
        for m in MODELS:
            e1.append(f"{SHORT[m]} & AIA / LIL / DSCR & -- & -- & -- & -- & -- \\\\")
            e2.append(f"{SHORT[m]} & AIA / LIL / DSCR & -- & -- & -- & -- & -- \\\\")
            e3.append(f"{SHORT[m]} & -- & -- & -- & -- & -- \\\\")
            e5.append(f"{SHORT[m]} & -- & -- & -- & -- & -- \\\\")
    # scalar macros for the prose: vfour<Est><Field><Phase><Model>, e.g. \\vfourEoneOwnAIAScout; control model tag is Gemini
    if st and st.get("models"):
        def put(est, field, ph, model, val, fmt=f1):
            mc.add(f"vfour{est}{field}{ph}{TAG[model]}", fmt(val))
        for m, r in {**st["models"], **st.get("controls", {})}.items():
            for ph, v in r.get("E1", {}).items():
                for fld, val in (("Own", v["acc_a"]), ("Text", v["acc_b"])):
                    put("Eone", fld, ph, m, val)
                put("Eone", "Diff", ph, m, v["diff"], signed)
                put("Eone", "Lo", ph, m, v["ci"][0], signed)
                put("Eone", "Hi", ph, m, v["ci"][1], signed)
                if "p_holm" in v:
                    mc.add(f"vfourEoneHolm{ph}{TAG[m]}", f"{v['p_holm']:.2f}")
                put("Eone", "SLo", ph, m, v["ci_sparse"][0], signed)
                put("Eone", "SHi", ph, m, v["ci_sparse"][1], signed)
                mc.add(f"vfourEoneP{ph}{TAG[m]}", pfmt(v["p"]))
                mc.add(f"vfourEoneOnlyOwn{ph}{TAG[m]}", v["only_a"])
                mc.add(f"vfourEoneOnlyText{ph}{TAG[m]}", v["only_b"])
            for ph, v in r.get("E2", {}).items():
                put("Etwo", "Gain", ph, m, v["gain"], signed)
                put("Etwo", "Lo", ph, m, v["gain_ci"][0], signed)
                put("Etwo", "Hi", ph, m, v["gain_ci"][1], signed)
                put("Etwo", "SLo", ph, m, v["gain_ci_sparse"][0], signed)
                put("Etwo", "SHi", ph, m, v["gain_ci_sparse"][1], signed)
                mc.add(f"vfourEtwoP{ph}{TAG[m]}", pfmt(v["gain_p"]))
                if "gain_p_holm" in v:
                    mc.add(f"vfourEtwoHolm{ph}{TAG[m]}", pfmt(v["gain_p_holm"]))
                put("Etwo", "Swap", ph, m, v["swap_answers_donor_key"])
                put("Etwo", "Changes", ph, m, v["swap_flips_answer_vs_own"])
        for m, r in sup.items():          # donor dependence of E2 (post hoc)
            for ph, v in r.get("donor_dependence", {}).items():
                mc.add(f"vfourDonorLo{ph}{TAG[m]}", signed(v["cluster_ci"][0]))
                mc.add(f"vfourDonorHi{ph}{TAG[m]}", signed(v["cluster_ci"][1]))
                mc.add(f"vfourDonorLooLo{ph}{TAG[m]}", signed(v["loo_donor_min"]))
                mc.add(f"vfourDonorLooHi{ph}{TAG[m]}", signed(v["loo_donor_max"]))
                mc.add(f"vfourDonorPerm{ph}{TAG[m]}", pfmt(v["perm_p"]))
                mc.add(f"vfourDonorN{ph}{TAG[m]}", v["distinct_donors"])
                mc.add(f"vfourDonorMax{ph}{TAG[m]}", v["max_uses"])
        for m, r in st["models"].items():
            e = r.get("E3", {})
            t = TAG[m]
            for cond, nm in (("ctx_gold", "Gold"), ("ctx_wrong", "Wrong"), ("ctx_absent", "Absent")):
                if cond in e:
                    mc.add(f"vfourEthree{nm}{t}", f1(e[cond]["acc"]))
            if "flip_label" in e:
                mc.add(f"vfourEthreeLabel{t}", f1(e["flip_label"]["follows_rule_after_flip"]))
            pdw = e.get("flip_window", {}).get("progressive_disease_items")
            if pdw:
                mc.add(f"vfourEthreeTiming{t}", f1(pdw["follows"]))
            if "ctx_gold" in e:
                for cls in ("continue", "confirm", "escalate"):
                    if f"acc_{cls}" in e["ctx_gold"]:
                        mc.add(f"vfourEthreeGold{cls.capitalize()}{t}", f"{e['ctx_gold'][f'acc_{cls}']['acc']:.0f}")
            for ph in ("TCM",):
                for name, cell in r.get("E4", {}).get(ph, {}).items():
                    key = {"gold_minus_wrong": "GoldWrong", "gold_minus_absent": "GoldAbsent"}.get(name)
                    if key:
                        mc.add(f"vfourEfour{key}Diff{t}", signed(cell["diff"]))
                        mc.add(f"vfourEfour{key}Lo{t}", signed(cell["ci"][0]))
                        mc.add(f"vfourEfour{key}Hi{t}", signed(cell["ci"][1]))
            g = r.get("E5", {}).get("ctx_gold")
            if g:
                mc.add(f"vfourEfiveSkill{t}", f"{g['skill']:+.3f}".replace("-", "$-$"))
                mc.add(f"vfourEfiveBrier{t}", f"{g['brier']:.3f}")
                mc.add(f"vfourEfiveAuc{t}", f"{g['auc']:.2f}")
                mc.add(f"vfourEfiveMid{t}", f"{100 * g['answer_counts'].get('C', 0) / g['n']:.0f}")
            for ph, v in r.get("E6", {}).items():
                mc.add(f"vfourEsixDiff{ph}{t}", signed(v["diff"]))
                mc.add(f"vfourEsixLo{ph}{t}", signed(v["ci"][0]))
                mc.add(f"vfourEsixHi{ph}{t}", signed(v["ci"][1]))
        ctrl = st.get("controls", {}).get("Gemini-3.6-Flash")
        if ctrl:
            crows = []
            for ph in ("AIA", "LIL", "DSCR"):
                a, b = ctrl["E1"][ph], ctrl["E2"][ph]
                crows.append(f"{PTAG.get(ph, ph)} & {a['n']} & {f1(a['acc_a'])} & {f1(a['acc_b'])} & {signed(a['diff'])} [{signed(a['ci'][0])}, {signed(a['ci'][1])}] & "
                             f"{f1(b['swap_answers_donor_key'])} & {signed(b['gain'])} [{signed(b['gain_ci'][0])}, {signed(b['gain_ci'][1])}] \\\\")
            (OUT / "tab_v4_ctrl.tex").write_text(tabular("lrrrlrl", ["Phase & $n$ & Image & Text-only & $\\Delta$ [95\\% CI] & Swap: donor key & Gain [95\\% CI] \\\\"], crows))
            mc.add("vfourCtrlEmpty", ctrl["empty_responses"])
            mc.add("vfourCtrlRecords", ctrl["n_records"])
    heads = {
        "e1": ("llrrrllrrl", ["Model & Phase & $n$ & Image & Text-only & $\\Delta$ [95\\% CI] & Add-half CI & Exact $p$ & Answers differ & Interval \\\\"]),
        "e2": ("llrrrrllrr", ["Model & Phase & $n$ & Own & Swap: donor & Text: donor & Gain [95\\% CI] & Add-half CI & Exact $p$ & Swap changes \\\\"]),
        "e3": ("lccccc", [" & \\multicolumn{3}{c}{TCM acc.\\ (\\%)} & \\multicolumn{2}{c}{Moved / informative} \\\\",
                         "\\cmidrule(lr){2-4}\\cmidrule(lr){5-6}", " & true & wrong & none & label (all) & timing (PD) \\\\"]),
        "e5": ("lcccccc", ["Model & $n$ & Brier & Base rate & Skill & $\\Delta$ Brier [95\\% CI] & AUC \\\\"]),
    }
    for name, rows in (("e1", e1), ("e2", e2), ("e3", e3), ("e5", e5)):
        cs, hd = heads[name]
        (OUT / f"tab_v4_{name}.tex").write_text(tabular(cs, hd, rows, zebra=(name != "e1")))


def donor_validation(mc: "Macros") -> None:
    """Macros + table for the donor-protocol validation with known-behaviour predictors (Appendix)."""
    dv = load("results/lumiere_v4_donor_validation.json")
    if not dv or "DSCR" not in dv:
        return
    LABEL = {"constant": "Constant answer", "random": "Random answer",
             "image_shift": "Generic image shift", "tracker_rho1": "Tracker ($\\rho=1$)",
             "tracker_rho0.7": "Tracker ($\\rho=0.7$)", "tracker_rho0.4": "Tracker ($\\rho=0.4$)"}
    TAGS = {"image_shift": "Shift", "tracker_rho1": "TrackFull", "tracker_rho0.7": "TrackMid",
            "tracker_rho0.4": "TrackLow", "constant": "Const", "random": "Rand"}
    d = dv["DSCR"]
    pr = d.get("predictors", {})
    mc.add("vfourDonorValN", d.get("n_recipients", ""))
    mc.add("vfourDonorValSims", pr.get("tracker_rho1", {}).get("sims", ""))
    for name, tag in TAGS.items():
        p = pr.get(name, {})
        if not p:
            continue
        mc.add(f"vfourDonorVal{tag}Gain", signed(p["gain_median"]))
        mc.add(f"vfourDonorVal{tag}Detect", f"{100 * p['detection_rate']:.0f}")
    # per-phase detection for AIA/LIL (to back the "same separation" claim with numbers)
    for ph in ("AIA", "LIL"):
        pp = dv.get(ph, {}).get("predictors", {})
        for name, tag in (("image_shift", "Shift"), ("tracker_rho0.4", "TrackLow")):
            p = pp.get(name, {})
            if p:
                mc.add(f"vfourDonorVal{tag}Detect{ph}", f"{100 * p['detection_rate']:.0f}")
    rows = []
    for name in ("constant", "random", "image_shift", "tracker_rho1", "tracker_rho0.7", "tracker_rho0.4"):
        p = pr.get(name)
        if not p:
            continue
        rows.append(f"{LABEL[name]} & {signed(p['gain_median'])} & {100 * p['detection_rate']:.0f}\\% \\\\")
    (OUT / "tab_v4_donorval.tex").write_text(tabular("lrr", ["Synthetic predictor & Donor gain (pp) & Detected ($p<.05$) \\\\"], rows))


def check_stale() -> list[str]:
    tex = Path("paper/latex/acl_latex.tex").read_text()
    return [pat for pat in STALE if re.search(pat, tex)]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--v4-only", action="store_true", help="regenerate only the tables and macros of the intervention study (what the anonymous artifact ships)")
    ap.add_argument("--out", default=None, help="output directory (default paper/latex/generated)")
    args = ap.parse_args()
    if args.out:
        global OUT
        OUT = Path(args.out)
    mc = Macros()
    if not args.v4_only:
        cohort(mc)
        v3_tables(mc)
        v3_appendix(mc)
    v4(mc)
    v4_supplement(mc)
    v4_inputcheck(mc)
    donor_validation(mc)
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "numbers.tex").write_text(mc.tex())
    (OUT / "numbers.json").write_text(json.dumps(mc.d, indent=1, sort_keys=True))
    print(f"wrote {len(mc.d)} macros and tables to {OUT}")
    if args.check:
        bad = check_stale()
        if bad:
            raise SystemExit(f"stale numbers still in acl_latex.tex: {bad}")
        print("no stale numbers found")


if __name__ == "__main__":
    main()
